// actionTypes.js

export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const CREATE_NEW_CONTACT = 'CREATE_NEW_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';

// >>>>>>>>>
export const FETCH_CONTACTS_PENDING = 'FETCH_CONTACTS_PENDING';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR';
// >>>>>>>>>
export const POST_CONTACT_PENDING = 'POST_CONTACT_PENDING';
export const POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS';
export const POST_CONTACT_ERROR = 'POST_CONTACT_ERROR';
// >>>>>>>>>
export const POST_DELETE_CONTACT_PENDING = 'POST_DELETE_CONTACT_PENDING';
export const POST_DELETE_CONTACT_SUCCESS = 'POST_DELETE_CONTACT_SUCCESS';
export const POST_DELETE_CONTACT_ERROR = 'POST_DELETE_CONTACT_ERROR';